baseURL = 'https://dzakki.github.io/'
languageCode = 'en-us'
title = 'Dzakki'
theme = 'hugo-bearblog'
description = "Hi, Dzakki disini! Belajar coding sejak umur 16 dan sekarang menjadi Software Engineer. Lagi belajar untuk menulis, melakukan banyak eksperimen dan suka mengajar."
license = "MIT"
licenselink = "https://github.com/dzakki/dzakki.github.io/tree/main/LICENSE"